services:
  app:
    container_name: app
    build: .
    stop_signal: SIGINT
  prometheus-server:
    container_name: prometheus-server
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.9
    ports:
      - "3000:3000"
